substitutions:
  _AGG_WINDOW: "60"
  _ALERT_WINDOW: "1"
  _REGION: "us-central1"
  _BUCKET: "dataflow-test-ranchana"

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:    
      - ./run_pipeline.sh

timeout: 1200s

options:
  CLOUD_LOGGING_ONLY



