substitutions:
  _AGG_WINDOW: "60"
  _ALERT_WINDOW: "1"
  _REGION: "us-central1"
  _BUCKET: "dataflow-test-ranchana"

steps:
  - name: 'python:3.10-slim'
    entrypoint: bash
    args:    
      - -c
      - |
        #!/bin/bash
        export AGG_WINDOW=$_AGG_WINDOW
        export ALERT_WINDOW=$_ALERT_WINDOW
        export REGION=$_REGION
        export BUCKET=$_BUCKET
        ./run_pipeline.sh

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY



