substitutions:
  _AGG_WINDOW: "10"
  _ALERT_WINDOW: "1"
  _REGION: "us-central1"
  _BUCKET: "dataflow-test-ranchana"
  _PROJECT_ID: "rugged-precept-451103-n9"
  _PROJECT_NUMBER: "1046723826220"

steps:
  - name: 'python:3.10-slim'
    entrypoint: bash
    args:    
      - -c
      - |
        #!/bin/bash
        export AGG_WINDOW=$_AGG_WINDOW
        export ALERT_WINDOW=$_ALERT_WINDOW
        export REGION=$_REGION
        export BUCKET=$_BUCKET
        export PROJECT_ID=$_PROJECT_ID
        export SERVICE_ACCOUNT_EMAIL="${_PROJECT_NUMBER}-compute@developer.gserviceaccount.com"
        chmod +x run_pipeline.sh
        ./run_pipeline.sh

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY



